### ISSUE TITLE
Hella LED Marker lights for exhausts

### ISSUE THREAD

**Issue by davidzoli** [50k-Customs/50k-addons#1]
May I ask to add the "exhaust_l" and "exhaust_r" to the Hella LED Marker White and Orange lights officially?
I want them on the side bars under the sideskirts (Elegance and Ranger) on the 2016 Scania trucks.

**Comment by simon50keda** [comment]
Fixed with 78947a7387f43d8a3434a406f8daae6973f6dd1a
