### ISSUE TITLE
8x4 Chassis

### ISSUE THREAD

**Issue by DLM333** [50k-Customs/50k-addons#2]
Would you consider taking the hibar to the new 8x4 Scania chassis? None of the default lightbars allow to place horns on the back of the cab like yours does. That'd be great! Thanks 😃

**Comment by simon50keda** [comment]
Sure, once 1.31 is release, I will update it.

**Comment by DLM333** [comment]
Awesome! Thank you.

**Comment by simon50keda** [comment]
Fixed with 25dc5c2d4dd3439976354923eca38cc82ab1ea1f
